# Generated by Django 5.2.8 on 2025-11-06 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('last_payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='آخر تاريخ دفع')),
                ('is_paid', models.BooleanField(default=True, verbose_name='تم الدفع')),
            ],
        ),
    ]
